# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: timescale/timescaledb-ha:pg17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hilostory_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      ERLANG_VERSION: 28.3.1
      ELIXIR_VERSION: 1.19.5-otp-28
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix

      - uses: actions/cache@v5
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ env.ERLANG_VERSION }}-${{ env.ELIXIR_VERSION }}

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.ERLANG_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - run: mix deps.get --check-locked
      - run: mix deps.compile
      - run: mix compile
      - run: mix test

  check-if-deploy:
    name: Check if deployment required
    runs-on: ubuntu-latest
    needs: test
    outputs:
      should-deploy: ${{ steps.check-changes.outputs.should-deploy }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check if changes require a deployment
        id: check-changes
        run: |
          deployable_paths='
          .github/workflows/fly-deploy.yml
          assets/css
          assets/scripts
          assets/ts
          assets/bun.lock
          assets/package.json
          config/config.exs
          config/prod.exs
          config/runtime.exs
          lib
          priv
          rel
          Dockerfile
          fly.toml
          mix.exs
          mix.lock
          '

          # Joining the deployable paths into a grep-compatible regex pattern
          joined_paths=$(echo "$deployable_paths" |
              sed '/^[[:space:]]*$/d' | # Trim empty lines
              sed 's/\./\\\./g' |        # Escape dots globally
              tr '\n' '|' |               # Join patterns with pipes
              sed 's/|$//'                 # Remove trailing pipe
          )

          # Get the list of changed files
          diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Check for matches with grep directly
          grep_regex="^($joined_paths)"
          if echo "$diff" | grep -qE $grep_regex; then
            echo "Will require a deployment because the following files changed:"
            echo "$diff" | grep -E $grep_regex

            echo "should-deploy=true" >> $GITHUB_OUTPUT
          else
            echo "No changed files require a deployment"

            echo "should-deploy=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    needs: check-if-deploy
    if: needs.check-if-deploy.outputs.should-deploy == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: hilostory
          SENTRY_PROJECT: hilostory
        with:
          environment: production
          release: ${{ github.sha }}
      - run: flyctl deploy --remote-only --build-arg RELEASE=${{ github.sha }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
